---
- name: copy performance.cnf template to apply optimizations to mariadb
  template: src=performance.cnf.j2 dest=/etc/my.cnf.d/performance.cnf owner=root group=root mode=0600
  notify: restart mariadb
