---
- name: Install mariadb repository
  template: src=templates/MariaDB.repo.j2 dest=/etc/yum.repos.d/MariaDB.repo owner=root group=root mode=0644

- name: Ensure Mariadb Package is installed
  yum: name={{ item }} state=present
  with_items:
    - MariaDB-server
    - MariaDB-client

- name: Ensure python-mysqldb is installed - required to control mysql from ansible
  yum: name=MySQL-python state=present

- name: Ensure MariaDB is running and start at boot
  service: name=mariadb.service state=started enabled=yes
