---
- name: Get MySQL version.
  command: 'mysql --version'
  register: mysql_cli_version
  changed_when: false

#- name: Create mysql root pass
#  command: /usr/bin/openssl rand -base64 16
#  register: mysql_root_passwd

- name: Delete anonymous MySQL server user for {{ ansible_hostname }}
  mysql_user: user="" host="{{ ansible_hostname }}" state=absent

- name: Delete anonymous mysql user for local host
  mysql_user: name="" state=absent

- name: Remove mysql test database
  mysql_db: name=test state=absent


- name: Disallow root login remotely
  command: 'mysql -NBe "{{ item }}"'
  with_items:
    - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1')
  changed_when: false

- name: Get list of hosts for the root user.
  command: mysql -NBe 'SELECT Host FROM mysql.user WHERE User = "root" ORDER BY (Host="localhost") ASC'
  register: mysql_root_hosts
  changed_when: false
  always_run: true

#- name: update mysql root passwd
#  mysql_user: login_user=root login_password='' name=root host=127.0.0.1 password={{ mysql_root_password  }}
# Note: We do not use mysql_user for this operation, as it doesn't always update
# the root password correctly. See: https://goo.gl/MSOejW
# Set root password for MySQL >= 5.7.x.
- name: Update MySQL root password for localhost root account
  shell: >
    mysql -u root -NBe 'update user set password=PASSWORD("{{ db_root_password }}") where User="{{ db_root_user }}";' mysql
  with_items: "{{ mysql_root_hosts.stdout_lines }}"
  #when: (mysql_root_password_update) and ('5.7.' in mysql_cli_version.stdout)
#    'ALTER USER "{{ mysql_root_username }}"@"{{ item }}" IDENTIFIED BY "{{ mysql_root_password }}";'



#- name: update mysql root passwd
#  mysql_user: login_user=root login_password=''
#    name=root
#    host=\"{{ item }}\" password={{ mysql_root_password  }}
#    priv=*.*:ALL,GRANT
#  with_items:
#    - \"{{ ansible_hostname }}\"
#    - 127.0.0.1
#    - ::1
#    - localhost

#- name: copy user my.cnf file with root passwd credentials
#  template: src=performance.cnf.j2 dest=/root/.my.cnf owner=root group=root mode=0600



