---
- name: Ensure phpMyAdmin is installed
  yum: name=phpmyadmin enablerepo=remi,remi-php{{ php_version }} state=present

- name: Enforce phpMyAdmin settings file
  template: src=templates/phpMyAdmin.conf.j2 dest=/etc/httpd/conf.d/phpMyAdmin.conf owner=root group=root mode=0644

